### ISSUE TITLE
notation of A as "a"

### ISSUE THREAD

**Issue by 000masa000** [xenharmonic-devs/sonic-weave#174]
Hi, I find the inconsistency of a lower case "a" note name kind of confusing. Augmented and Diminished are commonly aug and dim could they not be lower case a and d (I do not think this makes a conflict with m and M meaning small and large....)

**Comment by frostburn** [comment]
Aug and dim are too long. SonicWeave is intended for relative scales so relative notation takes precedence IMO. Reverting your changes now.
If others agree with `a4` to mean augmented fourth. Voice your support now.

**Comment by 000masa000** [comment]
My vote for a4 === augmented 4th

**Comment by frostburn** [comment]
There has been little discussion of this on Discord. Could go either way. Prior art says that `A4` is augmented:
https://www.yacavone.net/xen-calc/?q=A4

@000masa000 Would your peers recognize `a4` as augmented? Is there prior art of it in your line of music tradition?

**Comment by 000masa000** [comment]
Hi, my initial response is that the note names ought to have a completely consistent syntax, and I personally find this more confusing/error-prone than the interval case. I think the relative (interval) abbreviations are in principle less fixed. "aug" and "dim" are traditionally used consistently in lower-case, but you are right that the single-letter abbreviation is often "d" and "A".  I wonder if there is a good all-round solution? I understand you want to avoid going to maj min dim aug .... but these would be at least unambiguous

**Comment by 000masa000** [comment]
Fb4 Gb4 A4 should be three notes with intervals P1 M2 aug3, easy to read compared to Fb4 Gb4 a4 and P1 M2 A3, which looks like a note.

**Comment by frostburn** [comment]
I do find the note name argument strong. I guess we can deviate from xen-calc.

There was one tongue-in-cheek argument for using the Greek `Α` to fill in the visual gap left by the machine parser.

**Comment by arseniiv** [comment]
Wait I was joking about greek Α if it’s about mine. (Will discuss where appropriate.)

**Comment by frostburn** [comment]
Linking this issue to be closed with the PR. `Aug4` and `dim5` are later dealt in #192 .
