### ISSUE TITLE
Enable evaluation of step strings

### ISSUE THREAD

**Issue by inthar-raven** [xenharmonic-devs/sonic-weave#188]
The syntax would be something like `evaluateStepString(stepString: string, sizes: number[])`.

`evaluateStepString(LLsLLLs, [L: 9/8, s: 256/243])` would result in Pythagorean Ionian.

**Comment by frostburn** [comment]
SonicWeave doesn't have objects/dictionaries. If you want those I'm inclined to the syntax `{L: 9/8, s: 256/243}`. That should be a separate issue, though.

As for current state of affairs: `realizeStepString("LLsLLLs", [9/8, 256/243])` is possible to implement.

**Comment by frostburn** [comment]
We could also use makeshift records like:
```js
realizeStepString("XXyXXXy", [["X", 9/8], ["y", 256/243]])
```
One of the steps should be omittable to stack up to an octave by default e.g. 
```js
realizeStepString("XXyXXXy", [["X", 9/8]])
```
would produce the same result.
