### ISSUE TITLE
Unify enumerations and harmonic segments

### ISSUE THREAD

**Issue by frostburn** [xenharmonic-devs/sonic-weave#194]
**0.5° 🍵** — _Today at 6:20 PM_

> [...] does `1:3::7:11:14::17` work as expected?

**Comment by arseniiv** [comment]
If it ever goes picked up, here’s my idea how it could work in general and not just with integers (as `:` allows everything right now).

Yield everything that’s written in the specified order, but also when a `x::y` part is reached, yield all integers inside an open segment (*x*; *y*), i. e. everything in a closed segment [floor(*x*) + 1; ceil(*y*) − 1]. This pretty conservative extension should generalize both current `x:y:`…`:z` and `x::y`.

So despite I called `x::y` translating into `x:niente:y` being a joke, something like that can indeed be used when translating the code and at runtime when generating elements of this collection:
- on parse, at `::` emit an “inter-sentinel” into the parsed representation;
- if a “inter-sentinel” is reached on iteration, look at the previous yielded interval and the next to-be-yield interval (exist by parse guarantees) and yield all integer inbetweens.

If there is a quick `len` implementation for current `x:y:`…`:z` and `x::y`, then this generalized case is tougher but is still approachable. And it can also be that `len` is guaranteed to be O(1) *only* for these two kinds of enumerations and not for general ones.

**Comment by frostburn** [comment]
I don't think `4::7::16` should be legal. It doesn't add anything in terms of expressivity and becomes ambiguous when the segment misses its endpoint like in `(7/3)::8`.

So the the grammar should be (`x` or `y::z`) separated by colons.
