### ISSUE TITLE
Infer octave domain and formatting in stdlib helpers

### ISSUE THREAD

**Issue by frostburn** [xenharmonic-devs/sonic-weave#398]
E.g `rank2(3/2, 4)` should result in `2/1` octave while `rank2(7\12, 4)` should result in `12\12` octave.

**Comment by frostburn** [comment]
Would overloading `al` be too much?
```ocaml
2 al 3/2  (* 2/1 *)
2 al P5   (* P8 *)
2 al 7\12 (* 12\12 *)
```

**Comment by arseniiv** [comment]
Nice; what did `al` do before overloading?
